### ISSUE TITLE
Docker Argus.db Bind Mount

### ISSUE THREAD

**Issue by thickconfusion** [release-argus/Website#48]
Docker instructions include a volume mount for the db:

    volumes:
      - /path/to/local/config.yml:/app/config.yml
      - /path/to/storage/argus.db:/app/data/argus.db

However, I kept seeing Docker creating volumes for this. Upon closer examination, the container is actually mounting "/app/data", not strictly "/app/data/argus.db". Therefore, an anonymous bind mount is created each time.

Perhaps change the code so that only argus.db is mounted to the host instead of /app/data entirely; otherwise, change documentation to indicate this.
![image](https://github.com/release-argus/Website/assets/46466294/1bc4c419-078a-4604-afbf-8daf1579d6f4)

```
version: '3.7'

services:
  argus:
    image: releaseargus/argus:latest
    container_name: argus
    volumes:
      - ./config.yml:/etc/argus/config.yml
      - ./argus.db:/app/data/argus.db
```
